base_images:
  ocp_4.19_base-rhel9:
    name: "4.19"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.23-openshift-4.19:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.23-openshift-4.19
build_root:
  from_repository: true
releases:
  initial:
    integration:
      name: "4.19"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.19"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: default-catalog-consistency
  cron: 0 */4 * * *
  steps:
    test:
    - as: default-catalog-tests
      commands: |
        cd openshift/default-catalog-consistency
        REGISTRY_AUTH_FILE=/var/run/secrets/ci.openshift.io/cluster-profile/pull-secret
        make test-catalog
      from: src
      resources:
        requests:
          cpu: 100m
zz_generated_metadata:
  branch: main
  org: openshift
  repo: operator-framework-operator-controller
  variant: periodics
